-- AddEnumValue: add BACKUP_DOWNLOADED and ASSET_DELETED to AuditAction
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'BACKUP_DOWNLOADED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'ASSET_DELETED';
